// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: upper.proto

package upper

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UpperServiceClient is the client API for UpperService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpperServiceClient interface {
	ToUpper(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type upperServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpperServiceClient(cc grpc.ClientConnInterface) UpperServiceClient {
	return &upperServiceClient{cc}
}

func (c *upperServiceClient) ToUpper(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/upper.UpperService/ToUpper", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpperServiceServer is the server API for UpperService service.
// All implementations must embed UnimplementedUpperServiceServer
// for forward compatibility
type UpperServiceServer interface {
	ToUpper(context.Context, *Message) (*Message, error)
	mustEmbedUnimplementedUpperServiceServer()
}

// UnimplementedUpperServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUpperServiceServer struct {
}

func (UnimplementedUpperServiceServer) ToUpper(context.Context, *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToUpper not implemented")
}
func (UnimplementedUpperServiceServer) mustEmbedUnimplementedUpperServiceServer() {}

// UnsafeUpperServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpperServiceServer will
// result in compilation errors.
type UnsafeUpperServiceServer interface {
	mustEmbedUnimplementedUpperServiceServer()
}

func RegisterUpperServiceServer(s grpc.ServiceRegistrar, srv UpperServiceServer) {
	s.RegisterService(&UpperService_ServiceDesc, srv)
}

func _UpperService_ToUpper_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpperServiceServer).ToUpper(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/upper.UpperService/ToUpper",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpperServiceServer).ToUpper(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// UpperService_ServiceDesc is the grpc.ServiceDesc for UpperService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpperService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "upper.UpperService",
	HandlerType: (*UpperServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ToUpper",
			Handler:    _UpperService_ToUpper_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "upper.proto",
}
